from app.models import db, follows, User, users_join

def seed_follows():
  follows1 = follows.insert().values(followerId=1, followedId=2)
  follows2 = follows.insert().values(followerId=2, followedId=3)
  follows3 = follows.insert().values(followerId=2, followedId=4)
  follows4 = follows.insert().values(followerId=2, followedId=5)
  follows5 = follows.insert().values(followerId=2, followedId=6)
  follows6 = follows.insert().values(followerId=3, followedId=5)
  follows7 = follows.insert().values(followerId=4, followedId=2)
  follows8 = follows.insert().values(followerId=4, followedId=3)
  follows9 = follows.insert().values(followerId=4, followedId=5)
  follows10 = follows.insert().values(followerId=4, followedId=6)
  follows11 = follows.insert().values(followerId=4, followedId=7)
  follows12 = follows.insert().values(followerId=5, followedId=2)
  follows13 = follows.insert().values(followerId=5, followedId=3)
  follows14 = follows.insert().values(followerId=5, followedId=4)
  follows15 = follows.insert().values(followerId=5, followedId=6)
  follows16 = follows.insert().values(followerId=6, followedId=2)
  follows17 = follows.insert().values(followerId=6, followedId=4)
  follows18 = follows.insert().values(followerId=6, followedId=5)
  follows19 = follows.insert().values(followerId=6, followedId=7)
  follows20 = follows.insert().values(followerId=7, followedId=3)
  follows21 = follows.insert().values(followerId=7, followedId=4)

  db.session.execute(follows1)
  db.session.execute(follows2)
  db.session.execute(follows3)
  db.session.execute(follows4)
  db.session.execute(follows5)
  db.session.execute(follows6)
  db.session.execute(follows7)
  db.session.execute(follows8)
  db.session.execute(follows9)
  db.session.execute(follows10)
  db.session.execute(follows11)
  db.session.execute(follows12)
  db.session.execute(follows13)
  db.session.execute(follows14)
  db.session.execute(follows15)
  db.session.execute(follows16)
  db.session.execute(follows17)
  db.session.execute(follows18)
  db.session.execute(follows19)
  db.session.execute(follows20)
  db.session.execute(follows21)
  db.session.commit()

def undo_follows():
  db.session.execute('TRUNCATE follows RESTART IDENTITY CASCADE;')
  db.session.commit()
